<?php

/**
 * @file
 * This is the module to make simple status messages.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function status_messages_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] = 'status_messages/status-messages';
}

/**
 * Implements hook_theme_registry_alter().
 */
function status_messages_theme_registry_alter(&$theme_registry) {
  $theme_registry['status_messages']['path'] = drupal_get_path('module', 'status_messages') . '/templates/misc';
}

/**
 * Implements hook_preprocess().
 */
function status_messages_preprocess(&$variables) {
  $config = \Drupal::config('status_messages.status_messages');
  $variables['time'] = $config->get('time');
  $variables['#attached']['drupalSettings']['time'] = $variables['time'];
}
