<?php

/**
 * @file
 * Geolocation Geometry country import.
 */

/**
 * Implements hook_install().
 */
function geolocation_geometry_open_canada_provinces_install() {
  /** @var \Drupal\geolocation_geometry_data\GeolocationGeometryDataManager $geometry_data_manager */
  $geometry_data_manager = \Drupal::service('plugin.manager.geolocation.geometrydata');
  $provinces_batch = $geometry_data_manager->getGemeotryDataBatch('open_canada_provinces');

  batch_set($provinces_batch);
  $batch =& batch_get();
  $batch['progressive'] = FALSE;
  return batch_process();
}

/**
 * Implements hook_uninstall().
 */
function geolocation_geometry_open_canada_provinces_uninstall() {
  $taxonomy_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $taxonomy_storage->delete($taxonomy_storage->loadByProperties(['vid' => 'geolocation_provinces_of_canada']));
}
