<?php

/**
 * @file
 * Geolocation Geometry country import.
 */

/**
 * Implements hook_install().
 */
function geolocation_geometry_natural_earth_us_states_install() {
  /** @var \Drupal\geolocation_geometry_data\GeolocationGeometryDataManager $geometry_data_manager */
  $geometry_data_manager = \Drupal::service('plugin.manager.geolocation.geometrydata');
  $states_batch = $geometry_data_manager->getGemeotryDataBatch('natural_earth_us_states');

  batch_set($states_batch);
  $batch =& batch_get();
  $batch['progressive'] = FALSE;
  return batch_process();
}

/**
 * Implements hook_uninstall().
 */
function geolocation_geometry_natural_earth_us_states_uninstall() {
  $taxonomy_storage = \Drupal::entityTypeManager()->getStorage('taxonomy_term');
  $taxonomy_storage->delete($taxonomy_storage->loadByProperties(['vid' => 'geolocation_us_states']));
}
